apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-enable-sctp
  namespace: open5gs-demo-acm
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: type
      operator: In
      values:
      - 5gcore
