apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 5g-core-macvlan
  namespace: open5gs-demo-acm-core
spec:
  config: |-
    {
      "name": "5g-core-macvlan",
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp8s0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 5g-core-macvlan
  namespace: open5gs-demo-acm-upf
spec:
  config: |-
    {
      "name": "5g-core-macvlan",
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp8s0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }

