---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- overlays/network-attachments


patchesStrategicMerge:
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
- network_attachment_device_patch.yaml
