apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: open5gs-demo-acm
    app.kubernetes.io/part-of: open5gs-demo-acm
    apps.open-cluster-management.io/reconcile-rate: medium
  name: open5gs-demo-acm-subscription
  namespace: open5gs-demo-acm
spec:
  channel: open5gs-demo-acm/open5gs-multi-deployment-demo-open5gs
  name: open5gs-5gcore-helm
  packageOverrides:
  - packageAlias: open5gs-5gcore-helm
    packageName: open5gs-5gcore-helm
  placement:
    placementRef:
      kind: PlacementRule
      name: open5gs-demo-acm-placement
  secondaryChannel: ""
