apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
      level: {{ .Values.open5gs.logger.level }}

    ausf:
      sbi:
      - dev: eth0
        port: 8099
        advertise: open5gs-ausf
    nrf:
     sbi:
      name: open5gs-nrf
      port: 8099
