apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
type: Opaque
stringData:
  dbname: open5gs
  username: mongo
  password: {{ .Values.mongodb.password }}
  admin-username: admin
  admin-password: {{ .Values.mongodb.adminPassword }}
