apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      serviceAccountName: 5gcore
      containers:
      - image: registry.redhat.io/rhscl/mongodb-36-rhel7
        name: open5gs-mongodb
        env:
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: admin-password
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: dbname
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: password
        ports:
        - containerPort: 27017
          name: mongodb
