apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    logger:
      level: {{ .Values.open5gs.logger.level }}

    db_uri: mongodb://${MONGODB_ADMIN_USER}:${MONGODB_ADMIN_PASSWORD}@mongodb-svc/admin
    udr:
      sbi:
       - dev: eth0
         port: 8099
         # advertise: open5gs-udr
    nrf:
     sbi:
      name: open5gs-nrf  
      port: 8099
