apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: open5gs-demo-acm
  namespace: open5gs-demo-acm
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - open5gs-demo-acm
