apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: network-attachment-config-policy-aws
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: network-attachment-config-policy-aws
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - default
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: k8s.cni.cncf.io/v1
            kind: NetworkAttachmentDefinition
            metadata:
              name: 5g-core-n4
              namespace: open5gs-demo-acm-core
            spec:
              config: |-
                {
                  "name": "5g-core-n4",
                  "cniVersion": "0.3.1",
                  "type": "bridge",
                  "ipam": {}
                }
        remediationAction: inform
        severity: low
  remediationAction: enforce
