---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   demo: open5gs

commonLabels:
  demo: open5gs

bases:
- ../operator

resources:
- 01-network-attachment-policies.yaml
- 02-network-attachment-policies.yaml
# - 02-network-placement-rule.yaml
- 03-placement-binding.yaml
