apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: deploy-policies-sctp-demo-acm
  namespace: deploy-policies-sctp-demo-acm
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - deploy-policies-sctp-demo-acm
