apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: deploy-policies-sctp-demo-acm
  name: deploy-policies-sctp-demo-acm-placement
  namespace: deploy-policies-sctp-demo-acm
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
