---
# Source: open5gs-5gcore-helm/templates/upf-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
      level: info

    upf:
        pfcp:
           dev: net1
        gtpu:
           dev: net1
        subnet:
          - addr: 10.45.0.1/16
            dev: ogstun
            dnn: internet
