---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   demo: open5gs

commonLabels:
  demo: open5gs

#bases:
#- ../../base

resources:
# - channel.yaml
- subscription.yaml
- placementrule.yaml

