# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: quay.io/xymox/open5gs-ubi8
    pullPolicy: Always
    tag: "v2.2.6-11-g27285a6"
  logger:
    level: info
  network: 10.45.0.1/16
  tundev: ogstun

#
# Change this for security reasons
#
mongodb:
  adminPassword: mongo
  password: mongo

webui:
  image:
    repository: quay.io/xymox/open5gs-webui-ubi8
    pullPolicy: Always
    tag: "v2.4.5"
  ingress:
    enabled: false
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        ## Set this to true in order to enable TLS on the ingress record
        tls: false

        ## Optionally specify the TLS hosts for the ingress record
        ## Useful when the Ingress controller supports www-redirection
        ## If not specified, the above host name will be used
        # tlsHosts:
        # - www.open5gs-epc.local
        # - open5gs-epc.local

        ## If TLS is set to true, you can declare what secret will store the key/certificate for TLS
        # tlsSecret: open5gs-epc.local-tls    

dnn: internet  

amf:
  mcc: 208
  mnc: 93
  tac: 7

  nodePort: 30412
# Primary/Native kubernetes interface
k8s:
 interface: eth0
