---
# Source: open5gs-5gcore-helm/templates/nrf-deploy.yaml
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  labels:
    epc-mode: nrf
spec:
  # clusterIP: None
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 8099
      targetPort: http2
---
# Source: open5gs-5gcore-helm/templates/nrf-deploy.yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf-deployment
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: nrf
    spec:  
      serviceAccountName: 5gcore
      containers:
        - name: nrf
          image: "quay.io/xymox/open5gs-ubi8:latest"
          imagePullPolicy: Always
          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]
          ports:
          - containerPort: 8099
            name: http2
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
