---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-enable-sctp-on-cluster
  namespace: open5gs-demo-acm
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: usage
      operator: In
      values:
      - open5gs
    - key: clusterType
      operator: In
      values:
      - standard
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-enable-sctp-on-sno
  namespace: open5gs-demo-acm
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: usage
      operator: In
      values:
      - open5gs
    - key: clusterType
      operator: In
      values:
      - sno

